<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cli_dashboard</name>
  <version>0.1.0</version>
  <description>Member 5 — CLI Dashboard, Tests, Launch, Rosbag</description>
  <maintainer email="m5@example.com">Member5</maintainer>
  <license>Apache-2.0</license>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>python3-click</exec_depend>
  <buildtool_depend>ament_python</buildtool_depend>
  <export><build_type>ament_python</build_type></export>
</package>
